2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_setup.py:_flush():69] setting env: {}
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_init.py:_log_setup():342] Logging user logs to /home/jet/Sandboxes/railway_drone/wandb/run-20211004_170641-lud3mehl/logs/debug.log
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_init.py:_log_setup():343] Logging internal logs to /home/jet/Sandboxes/railway_drone/wandb/run-20211004_170641-lud3mehl/logs/debug-internal.log
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_init.py:init():375] calling init triggers
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {'num_envs': 10, 'max_steps': 2000, 'buffer_size': 20000, 'buffer_size_debug': 100, 'batch_size': 300, 'start_epoch': 0, 'epochs': 10000, 'transitions_per_epoch': 3000, 'repeats_per_buffer': 5, 'scheduler_steps': 5, 'scheduler_gamma': 0.5, 'starting_LR': 0.001, 'reg_lambda': 0.01, 'weights_directory': 'weights', 'optim_weights_directory': 'optim_weights', 'tracknet_version': '_7', 'tracknet_number': 0, 'epoch_interval': 1, 'batch_interval': -1, 'debug': False, 'wandb': True, 'device': device(type='cuda', index=0), 'iter_per_epoch': 66, 'step_sched_num': 132000.0}
2021-10-04 17:06:41,412 INFO    MainThread:63464 [wandb_init.py:init():424] starting backend
2021-10-04 17:06:41,412 INFO    MainThread:63464 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-04 17:06:41,430 INFO    MainThread:63464 [backend.py:ensure_launched():135] starting backend process...
2021-10-04 17:06:41,445 INFO    MainThread:63464 [backend.py:ensure_launched():139] started backend process with pid: 63486
2021-10-04 17:06:41,448 INFO    MainThread:63464 [wandb_init.py:init():429] backend started and connected
2021-10-04 17:06:41,451 INFO    MainThread:63464 [wandb_init.py:init():477] updated telemetry
2021-10-04 17:06:41,452 INFO    MainThread:63464 [wandb_init.py:init():500] communicating current version
2021-10-04 17:06:42,004 INFO    MainThread:63464 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-04 17:06:42,005 INFO    MainThread:63464 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-04 17:06:42,301 INFO    MainThread:63464 [wandb_init.py:init():540] starting run threads in backend
2021-10-04 17:06:46,022 INFO    MainThread:63464 [wandb_run.py:_console_start():1584] atexit reg
2021-10-04 17:06:46,022 INFO    MainThread:63464 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-10-04 17:06:46,022 INFO    MainThread:63464 [wandb_run.py:_redirect():1463] Redirecting console.
2021-10-04 17:06:46,023 INFO    MainThread:63464 [wandb_run.py:_redirect():1519] Redirects installed.
2021-10-04 17:06:46,023 INFO    MainThread:63464 [wandb_init.py:init():565] run started, returning control to user process
2021-10-04 17:07:59,251 INFO    MainThread:63464 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-10-04 17:07:59,252 INFO    MainThread:63464 [wandb_run.py:_restore():1526] restore
2021-10-04 17:08:04,221 ERROR   MainThread:63464 [wandb_run.py:_atexit_cleanup():1572] Problem finishing run
Traceback (most recent call last):
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1562, in _atexit_cleanup
    self._on_finish()
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1698, in _on_finish
    self.history._flush()
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 885, in _history_callback
    self._backend.interface.publish_history(
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 223, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/util.py", line 669, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/jet/.local/lib/python3.8/site-packages/wandb/util.py", line 636, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Parameter is not JSON serializable
