
No weights directory for weights/Version_7, generating new one in 3 seconds.
No weights directory for optim_weights/Version_7, generating new one in 3 seconds.
No weights file found, generating new one during training.
[W python_anomaly_mode.cpp:104] Warning: Error detected in MulBackward0. Traceback of forward call that caused the error:
  File "src/mainSAC.py", line 261, in <module>
    train(set)
  File "src/mainSAC.py", line 116, in train
    rnf_loss, sup_loss, sup_scale, sup_norm = net.calc_actor_loss(states, auxiliary, dones, labels)
  File "/home/jet/Sandboxes/railway_drone/src/ai_lib/UASAC.py", line 179, in calc_actor_loss
    sup_loss = NIG_NLL(torch.atanh(labels), *output, reduce=False)
  File "/home/jet/Sandboxes/railway_drone/src/ai_lib/normal_inverse_gamma.py", line 60, in NIG_NLL
    twoBlambda = 2 * beta * (1 + nu)
 (function _print_stack)
Traceback (most recent call last):
  File "src/mainSAC.py", line 261, in <module>
    train(set)
  File "src/mainSAC.py", line 126, in train
    total_loss.backward()
  File "/home/jet/.local/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/jet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.
Traceback (most recent call last):
  File "src/mainSAC.py", line 261, in <module>
    train(set)
  File "src/mainSAC.py", line 126, in train
    total_loss.backward()
  File "/home/jet/.local/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/jet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.